### ISSUE TITLE
Built-in unary MaybeType from sanctuary causing errors when used in sig

### ISSUE THREAD

**Issue by Koleok** [sanctuary-js/sanctuary-def#87]
Recently I set my `sanctuary-def` dependency to pull from `#master` in order to avoid #85. When I did, I noticed that any signature i had defined using the built-in `S.MaybeType` that comes from sanctuary, was failing with something like the following

```bash
TypeError: Cannot read property 'length' of undefined
    at isEmpty (project-path/node_modules/sanctuary-def/index.js:74:41)
    at showType (project-path/node_modules/sanctuary-def/index.js:1192:63)
    at Array.map (native)
    at typeSignature (project-path/node_modules/sanctuary-def/index.js:1220:23)
    at curry (project-path/node_modules/sanctuary-def/index.js:1548:33)
    at def (project-path/node_modules/sanctuary-def/index.js:1576:14)
    at def (project-path/imports/utils/sanctuary/def.js:5:37)
    at project-path/imports/utils/sanctuary/def.js:8:23
    at Object.<anonymous> (project-path/my-file.js:67:45)
    at Module._compile (module.js:556:32)
    at loader (project-path/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (project-path/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (project-path/my-file.spec.js:11:20)
    at Module._compile (module.js:556:32)
    at loader (project-path/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (project-path/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at project-path/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (project-path/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (project-path/node_modules/mocha/lib/mocha.js:469:10)
    at loadAndRun (project-path/node_modules/mocha/bin/_mocha:360:22)
    at rerun (project-path/node_modules/mocha/bin/_mocha:387:5)
    at project-path/node_modules/mocha/bin/_mocha:395:7
    at StatWatcher.<anonymous> (project-path/node_modules/mocha/lib/utils.js:174:9)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1487:10)
```

I have a fork of the `ramda-repl` up where i was able to reproduce this behavior [here](https://goo.gl/dXC2W6) _(toggle the underscore on `ln:26` to see the difference)_

**Comment by davidchambers** [comment]
Sanctuary won't be compatible with the current state of `sanctuary-js/sanctuary-def:master` until sanctuary-js/sanctuary#232 is merged. I hope to merge that pull request within the next day or two.

**Comment by Koleok** [comment]
👌 I'll close this then
